dist: bionic

services:
  - rabbitmq

before_install:
  - sudo apt update
  - curl -fsS https://dlang.org/install.sh | bash -s dmd
  - sourcefile=$(ls ~/dlang/dmd-*/activate)
  - source $sourcefile
  - sudo apt install -y curl wget
  - sudo wget https://netcologne.dl.sourceforge.net/project/d-apt/files/d-apt.list -O /etc/apt/sources.list.d/d-apt.list
  - sudo apt-get update --allow-insecure-repositories && sudo apt-get -y --allow-unauthenticated install --reinstall d-apt-keyring && sudo apt-get update
  - sudo apt install -y dub
  - cat /etc/lsb-release
  - dmd --version
  - dub --version

  - sudo echo "deb http://neurodebian.ovgu.de/debian/ sid main contrib non-free" >> /etc/apt/sources.list
  - sudo apt-key adv --recv-keys --keyserver pool.sks-keyservers.net 0xA5D32F012649A5A9 || sudo apt-key adv --keyserver hkp://keys.gnupg.net --recv-keys 0xA5D32F012649A5A9 || sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 0xA5D32F012649A5A9
  - sudo apt update
  - sudo apt -y install rabbitmq-server wget dialog apt-utils python-boto python3-boto librabbitmq-dev librabbitmq

script:
  - dub test

branches:
  only:
    - master
